### ISSUE TITLE
CHAT has memory overrun errors

### ISSUE THREAD

**Issue by natturtle** [AndrewSav/focal-69#2]
When running CHAT under Visual Studio as C++, following lines got memory exceptions. Looks like it was converted from 1 .. MAXSTATES but in C and C++ it needs to be 0 .. MAXSTATES-1. I haven't checked the logic to see what happens at the upper boundary. 
in ilr0state () 
~~~
for (s = 1; s <= MAXSTATES; s++) lr0state.state[s] = 1;
lr0state.item[i].imarker = 0;
~~~
and slr1con()
~~~
reduce_lst[ndx].cnt = 0;
ptr_lst[ndx] = ndx;
goto_lst[ndx].cnt = 0;
~~~

**Comment by AndrewSav** [comment]
I do not think I ever tried to compile or run CHAT myself. I think we cannot do much here as it is not even part of this repo, what do you think? @natturtle

**Comment by AndrewSav** [comment]
Also I just compiled and ran CHAT on linux, I'm not seeing any errors. May be this is something specific to VS and Windows...

**Comment by natturtle** [comment]
FOCAL was the first computer language that I was introduced to. That's how I arrived at this repository.

CHAT seemed like a bonus, so I downloaded it too. I was very interested in how Dave Pitts incorporated the results from CHAT into FOCAL. Hoped to be able to learn about parsing from it. I have also found YACC, but there lots more pieces compared to CHAT, so it is a lot harder to get your head around.

I suspect CHAT is a quick and dirty implementation of a YACC subset. I agree with you that it isn't really part of the FOCAL repository, so it probably doesn't merit any work to update it. I spent some time this morning and discovered some differences between the CHAT routines and the routines included with FOCAL. I seem to be quickly disappearing down a rabbit hole here and this contradicts my reasons for getting involved with CHAT in the first place, I think we should both call it quits and move on.

I really wanted to be able to ask you whether Dave was still involved with Focal and might have had a later version of CHAT. GitHub didn't seem to allow me to just send a message to the repository owner, so I raised an issue - I hope you don't mind.

There are definitely coding errors in handling boundary cases, but the limits are generous and the effort to fix isn't worth the time.

**Comment by AndrewSav** [comment]
> I really wanted to be able to ask you whether Dave was still involved with Focal and might have had a later version of CHAT.

So same as for you focal was one of the first languages I learned as a kid and that's how I ended up creating this repo. I wrote an email to Dave, he responded with a great surprise, saying that no one showed interest in it for many years. I think this repo and the CHAT archive contains the final version of what Dave ended up with when he stopped working on this many years ago, It is very unlikely that there is a fresher version, based on my correspondence with him a few years ago.

> GitHub didn't seem to allow me to just send a message to the repository owner, so I raised an issue - I hope you don't mind.

All good.

**Comment by AndrewSav** [comment]
@natturtle, you may also find this: [akira.zip](https://github.com/AndrewSav/focal-69/files/9546703/akira.zip) interesting.

**Comment by natturtle** [comment]
@AndrewSav yes, that is 1995 and a different way of doing the parsing. Focal was such fun when I learnt it on a PDP-8. 

I saw that Dave worked on it to run under MVS, which is what I have worked on for the last 40 years. I got it up and running on MVS and have had a lot of fun with it. I suggest you close this issue.
